#!/bin/bash

echo " ---> [Dockito Vault] Downloading private keys..."

mkdir -p ~/.ssh/

curl -o ~/.ssh/id_rsa.pub http://172.17.42.1:14242/.ssh/id_rsa.pub
curl -o ~/.ssh/id_rsa http://172.17.42.1:14242/.ssh/id_rsa
echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

chmod 0600 ~/.ssh/id_rsa.pub
chmod 0600 ~/.ssh/id_rsa

echo " ---> [Dockito Vault] Executing command: $@"

eval $@

echo " ---> [Dockito Vault] Removing private keys..."

rm ~/.ssh/id_rsa.pub
rm ~/.ssh/id_rsa
rm ~/.ssh/config
