#!/bin/bash

# signals bash to stop execution on any fail
set -e

mkdir -p ~/.ssh/

echo " ---> [Dockito Vault] Downloading private keys..."

curl -s http://172.17.42.1:14242/ssh.tgz | tar xzf - -C ~

echo " ---> [Dockito Vault] Using key: `cat ~/.ssh/id_rsa.fingerprint`"
echo " ---> [Dockito Vault] Executing command: $@"

eval $@

echo " ---> [Dockito Vault] Removing private keys..."

rm -rf ~/.ssh/*
